import os
import sys

if len(sys.argv) != 2:
    print("Usage: cprj <project_name>")
    exit(1)

cwd = os.getcwd()
name = sys.argv[1]

project_dir = cwd + f"/{name}"
script_path = os.path.dirname(os.path.realpath(__file__))

if os.path.exists(project_dir):
    print(f"Directory {name} already exists in the current location", file=sys.stderr)
    exit(2)

# --------- DIRECTORIES --------- #
os.makedirs(project_dir + "/src")
os.makedirs(project_dir + "/include")
os.makedirs(project_dir + "/lib")

# ---------- MAKEFILE ---------- #
with open(f"{script_path}/example_makefile", "r") as f:
    text = f.read()

makefile = "# Autogenerated makefile\n\n" + text.replace("name", name)

with open(project_dir + "/makefile", "w") as f:
    f.write(makefile)

# ----------- MAIN.C ----------- #

with open(f"{script_path}/example_main.c", "r") as f:
    text = f.read()

main = "/* Autogenerated main.c file */\n\n" + text.replace("name", name)

with open(project_dir + "/src/main.c", "w") as f:
    f.write(main)

print(f"Created project {name}")

